version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: bash -c "npm install && npm run dev"
    ports:
      - "3001:3000"
